### PR TITLE
Update index.html Added a title for the page

### PR DESCRIPTION
**Pull request by Sheshank-s**

### CODE REVIEW

**Comment by hyperobject** [comment]
I'm not sure this is really necessary - can you explain how it improves the experience?

**Comment by Sheshank-s** [comment]
I thought it might look better :)

**Comment by coke11** [comment]
@technoboy10 You know how in the bar at the top of the page it shows the title of the page? This would make it show that. (I created another PR btw)

**Comment by TheGrits** [comment]
@GreenBayRules Thanks for wanting to help, but I don't think this is necessary either. Feel free to make other changes though! :)

**Pull request closed without merging**
