### PR TITLE
Added New Curators

### PR DESCRIPTION
**Pull request by coke11**
In case the automatic curator check fails.

### CODE REVIEW

**Comment by Hamish752** [comment]
@coke11 Yeah, looks good, although Ionosphere quit the team iirc.

**Review by TheGrits — CHANGES_REQUESTED** [review]
Looks good, except Ionosphere has left the team (for now).

**Comment by coke11** [comment]
Yeah. But I thought they came back to Scratch? They are in the current studio...

**Review by TheGrits — APPROVED** [review]

**Comment by TheGrits** [comment]
@coke11 Good call, I hadn't noticed they came back. Thanks!

**Comment by coke11** [comment]
no problem!

**Comment by coke11** [comment]
I know this PR is from a long time ago, but should we add the new curators for the manual check?

**Pull request merged**
