### PR TITLE
Studio Id

### PR DESCRIPTION
**Pull request by St19Galla**
Just an update to the studio id

### CODE REVIEW

**Comment by hyperobject** [comment]
Not sure this needs to be merged, since the studio ID automatically updates (see lines 3 and 4 of main.js).

**Comment by St19Galla** [comment]
Ah sorry :P I'm new at this, trying to learn. It took me forever trying to learn to create a poll request xD

**Comment by hyperobject** [comment]
No worries! Welcome to the crazy world of open source software. :)

**Comment by coke11** [comment]
@technoboy10 Then why was this updated? https://github.com/scratchdesignstudio/quick-link/commit/b2d5a2eeec9ce32fac6fb338b7d2747af3235ac0 - Was the script not working?

**Comment by TheGrits** [comment]
@coke11 I left you a comment on the commit that explains the situation I was in when I made that commit.

**Pull request closed without merging**
